name: baselineblocknetmultigraph
dataset: timeseriesdataset
hidden_dim: 64
num_blocks: 4
temporal_kernel_init_size: 3
lcorr_gru_dim: 64
lcorr_qk_dim: 32
lcorr_softmax_dim: 2
residual_conns: true
cheb_conv_k: 2 #set to 0 for just normal graph conv

